#! python3
#pw.py - an insecure password locker program
password={'email':'F7minlbDDuvMJ654sssh','blog':'VmaLQy7865G8vo1DMLZ','luggage':'12345'}
from sys import argv,exit()
if len(argv<2):
  print("Usage: python pw.py [account] - copy account password")
  exit()
 
account=sys.argv[1]
if account in password.keys():
  pyper.copy(password[account])
  print("password for  "+account='  copied to clipword')
else:
  print("there is no account named" + account)
  
